services:
  - name: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    public: true
    github:
      branch: main
